BUG: Fix mismatched columns
afids/afids-validator pull request #108
Opened 2021-02-01 20:11 UTC by kaitj

## Proposed changes

Resolves #93 

Error is thrown if `row_label` is not numerical / `row_desc` is empty. Adds check for both of these. 
Recommendation is to merge following #101 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionalitiy)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [x] Code has been run through [`black`](https://github.com/psf/black) with the `-l 79` flag.
- [x] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md)_

2021-02-01 20:13 UTC, kaitj commented
Just realized this includes all the commits from the `afids-class` PR so definitely don't merge until #101 is merged!

2021-02-03 15:20 UTC, tkkuehn requested changes
A couple of nitpicks but basically looks good.

If possible, it would be nice to change this PR to merge into the `afids-class` branch instead of `master` -- I think that would get rid of all the irrelevant commits.

2021-02-03 15:20 UTC, tkkuehn commented on model.py
> +        if not row_label.isdigit():
I'm a little surprised we don't already just check something like `row_label == str(expected_label)`, which would also cover this case. Assuming there's a good reason for that and I've forgotten it, this makes sense.

2021-02-03 15:20 UTC, tkkuehn commented on model.py
> +        # Check to see if row description is valid
I would maybe adjust this to say "Check to see row description is not empty or None".

2021-02-03 15:20 UTC, tkkuehn commented on model.py
> +                f"Row description {row_desc} is not a invalid for {row_label}"
Typo

2021-02-03 15:50 UTC, kaitj commented
> A couple of nitpicks but basically looks good.
> 
> If possible, it would be nice to change this PR to merge into the `afids-class` branch instead of `master` -- I think that would get rid of all the irrelevant commits.

Done!

2021-02-03 20:10 UTC, tkkuehn approved these changes
Looks good to me. Let's just wait until the AFIDs class is merged then merge this to master.

2021-03-03 20:07 UTC, merged