Bootstrap update
afids/afids-validator pull request #135
Opened 2021-05-27 14:05 UTC by kaitj

## Proposed changes

Resolves #132  - updates bootstrap to v5.0.1. Navbar and plotting tabs have been updated to make use of new/renamed classes and variables. Other changes include:
* Updated CSS to use only what is needed
* Updated `col-*` classes in `index.html` to use `col-*` instead of `col-sm-*`, which was originally meant for different screen sizes (e.g. mobile vs desktop)
* Centered the video within the `col-sm-5`
* Font size (which was not previously set), now set to 2.5% of viewport width for navigation headings
* Icon sizes in footer updates

I have also run ![`prettier`](https://prettier.io/) on the files I have touched, so some of the formatting may have changed from before.

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionalitiy)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [x] Code has been run through [`black`](https://github.com/psf/black) with the `-l 79` flag.
- [x] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md)_

2021-06-09 18:58 UTC, tkkuehn requested changes
Looking good, mostly small changes to think about. Thanks for taking care of this!

2021-06-09 18:58 UTC, tkkuehn commented on templates/base.html
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
Do we need jquery anymore? Not sure what we're using it for...

2021-06-09 18:58 UTC, tkkuehn commented on templates/base.html
> +    <script
This should go at the end of the body per [the docs](https://getbootstrap.com/docs/5.0/getting-started/introduction/#js).

2021-06-09 18:58 UTC, tkkuehn commented on static/css/afids_custom.css
> +  text-transform: uppercase;
Could set `.text-uppercase` on the links instead.

2021-06-09 18:58 UTC, tkkuehn commented on static/css/afids_custom.css
> +  font-size: 2vw;
I'd prefer to set this with a [bootstrap class](https://getbootstrap.com/docs/5.0/utilities/text/#font-size) or by making it a header.

2021-06-09 18:58 UTC, tkkuehn commented on static/css/afids_custom.css
> +  margin-right: 1vw;
Could set these with [`.mx-*`](https://getbootstrap.com/docs/5.0/utilities/spacing/#margin-and-padding) bootstrap classes.

2021-06-09 18:58 UTC, tkkuehn commented on static/css/afids_custom.css
> +  font-size: 1vw;
Could set this with bootstrap instead.

2021-06-09 19:12 UTC, kaitj commented on static/css/afids_custom.css
> +  margin-right: 1vw;
I forgot those exists - agree with using the bootstrap class if possible

2021-06-09 19:22 UTC, kaitj commented on static/css/afids_custom.css
> +  font-size: 2vw;
Set font-size static

2021-06-09 19:22 UTC, kaitj commented on static/css/afids_custom.css
> +  font-size: 1vw;
Font-size (see above)

2021-06-09 20:23 UTC, kaitj commented on templates/base.html
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
Removed in 2b1da4b

2021-06-09 20:23 UTC, kaitj commented on templates/base.html
> +    <script
Moved in 2b1da4b

2021-06-09 20:30 UTC, kaitj commented on static/css/afids_custom.css
> +  text-transform: uppercase;
Added `text-uppercase` class to the `nav` and removed from css in 8d73355

2021-06-09 20:38 UTC, kaitj commented on static/css/afids_custom.css
> +  font-size: 1vw;
Updated in 61627ea

2021-06-09 20:38 UTC, kaitj commented on static/css/afids_custom.css
> +  margin-right: 1vw;
Updated in 114ab99

2021-06-09 20:38 UTC, kaitj commented on static/css/afids_custom.css
> +  font-size: 2vw;
Updated in 14ab99

2021-06-09 20:40 UTC, kaitj commented
Everything seemed to be working without jquery so I am at a loss at what it was used for. Anyways, it is now removed and ready for another review.

2021-06-23 19:50 UTC, tkkuehn approved these changes
Looks good to me!

2021-06-23 20:13 UTC, merged