ENH: Python dotenv
afids/afids-validator pull request #146
Opened 2021-08-16 22:46 UTC by kaitj

## Proposed changes

Makes use of the `python-dotenv` library to grab the configuration variables from a `.env` file without need to export the file prior to use. These changes were originally made based on an old version of master. This PR includes a rebase from the `remaster-code` branch, which is just waiting to be merged at the next meeting. Local tests have this working.

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionalitiy)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ ] Code has been run through [`black`](https://github.com/psf/black) with the `-l 79` flag.
- [ ] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md)_

2021-09-01 20:47 UTC, tkkuehn requested changes
A few comments about the configuration setup but this otherwise looks reasonable to me!

2021-09-01 20:47 UTC, tkkuehn commented on manage.py
> +    from config import ProductionConfig
I would rather import `config` as a whole or import all the classes at the top than import selectively based on the environment.

2021-09-01 20:47 UTC, tkkuehn commented on manage.py
> +else:
I think it'd be safer to explicitly check for the string `"development"` then throw an exception if `FLASK_ENV` isn't properly defined.

2021-09-01 20:47 UTC, tkkuehn commented on manage.py
> +# Grab environment
I think I would rather have all this environment parsing stuff in `__init__.py` so all the configuration is defined in one place. Or make the `config_settings` an argument to `create_app`.

2021-09-01 20:47 UTC, tkkuehn commented on setup.py
> +        "python-dotenv==0.17.1",
`python-dotenv~=0.17`, maybe?

2021-09-01 21:02 UTC, kaitj commented on manage.py
> +# Grab environment
Moved all of it into `__init__.py`. Just seemed cleaner.

2021-09-01 21:02 UTC, kaitj commented on manage.py
> +    from config import ProductionConfig
That is fair, I've changed the import to `from config import *`

2021-09-01 21:03 UTC, kaitj commented on manage.py
> +else:
Sounds good to me. I've added an explicit check rather than default to the `DevelopmentConfig`

2021-09-02 18:44 UTC, tkkuehn commented
Looks like some of the changes you made didn't get pushed to github?

2021-09-02 18:57 UTC, kaitj commented
> @kaitj Looks like some of the changes you made didn't get pushed to github?

Huh that was weird. It was staged but never committed.

2021-09-03 13:55 UTC, tkkuehn requested changes
Sorry, a couple of minor things I missed the first time around but thought of when I tried this.

2021-09-03 13:55 UTC, tkkuehn commented on afidsvalidator/__init__.py
> +    config_setings = DevelopmentConfig
Do you mind instantiating the config classes (i.e. `DevelopmentConfig()` instead of `DevelopmentConfig`). Doesn't have any practical effect but pylint complains about it now.

2021-09-03 13:55 UTC, tkkuehn commented on afidsvalidator/__init__.py
> +    config_setings = DevelopmentConfig
Also: `config_setings` is a typo, should be `config_settings`.

2021-09-03 13:55 UTC, tkkuehn commented on afidsvalidator/__init__.py
> +# Grab environment
Can we raise an exception if FLASK_ENV isn't defined? Something like:
```python
if os.environ.get("FLASK_ENV") is None:
    # Raise an exception
```

2021-09-03 13:55 UTC, tkkuehn commented on afidsvalidator/__init__.py
> +    raise Exception("Invalid environment")
It would be nice to define a `ConfigException` class (or something) so we're not using the base `Exception` class.

2021-09-03 14:20 UTC, kaitj commented on afidsvalidator/__init__.py
> +# Grab environment
Done

2021-09-03 14:20 UTC, kaitj commented on afidsvalidator/__init__.py
> +    raise Exception("Invalid environment")
Added a new `ConfigException` within the __init__.py. Is there a better place for this?

2021-09-03 14:22 UTC, tkkuehn commented on afidsvalidator/__init__.py
> +    raise Exception("Invalid environment")
It's a little awkward but I do think `__init__.py` is the best place for it.

2021-09-03 14:26 UTC, tkkuehn approved these changes
Looks good to me!

2021-09-03 14:31 UTC, merged