React Frontend
afids/afids-validator pull request #205
Opened 2023-05-18 17:41 UTC by kaitj

## Proposed changes

Change to switch some of the frontend from pure HTML/CSS/JS to React+Typescript. Relatively minor changes here (primarily to the navbar and footer), but will be beneficial in the long run for building out an admin UI. Also fixes some visual discrepancies on the page.

One thing that needs to be checked / tested is the login/logout functionality since this was moved from Jinja (Flask) to React. Will also need to slightly change the deployment.

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionalitiy)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ ] Code has been run through [`black`](https://github.com/psf/black) with the `-l 79` flag.
- [ ] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md)_

2023-05-23 21:26 UTC, kaitj commented
I think the token for this also expired - the auto assignment of reviewers didn't work.

2023-05-25 14:45 UTC, tkkuehn commented on afidsvalidator/static/lib/afidsvalidator-react/src/components/NavBar.tsx
> +    <NavBar current_user={currentUser} />,
I don't super understand how this is supposed to work, but in my browser it complains that `currentUser` isn't defined. Could we make `currentUser` an argument to this function and pass it in the template instead of trying to assign it globally?

2023-05-25 14:46 UTC, tkkuehn commented on afidsvalidator/static/lib/afidsvalidator-react/src/components/NavBar.tsx
> +const NavBar: React.FC<{ current_user: string }> = ({ current_user }) => {
Javascript pretty much always uses camelCase, I think.

2023-05-25 18:37 UTC, kaitj commented on afidsvalidator/static/lib/afidsvalidator-react/src/components/Footer.tsx
> +const Footer: React.FC = () => {
Not opposed to changing it.

2023-05-25 19:00 UTC, kaitj commented on afidsvalidator/static/lib/afidsvalidator-react/src/components/NavBar.tsx
> +    <NavBar current_user={currentUser} />,
So this doesn't work at the moment and in the most recent pushes, I've just temporarily set this to `null`. Ultimately, need to pass the `current_user` from the backend to this, or rather whther or not there is a `current_user`. Can discuss more during next validator meeting.

2023-09-26 18:01 UTC, tkkuehn requested changes
All the react and templating stuff looks good to me, but I'd actually like to check in the `dist` subdirectory of `afidsvalidator-react` to make sure building from the github repository works properly

2023-09-27 16:30 UTC, merged