Draft Pull Request: Visualizations
afids/afids-validator pull request #89
Opened 2020-06-08 20:02 UTC by jakspacek

## Proposed changes
Add plotly interactive graphs to the Validator page.

## Notes
I have a good idea of the roadmap to fully integrate these, but I don't have the resources right now to test the changes properly myself.
- the routine `generate_visualizations()` (from generate_visualizations.py) should be called in controller.py's `validator()` (around line 405, maybe?)
- `generate_visualizations()` is equipped to dump working HTML to a file (specified by an argument) - it will be wrapped in a <body> etc but those are easy to trim out. It's approximately 3MB of javascript.
- Either `render_template()` (the call on line 406 of controller.py currently) can be modified to take another argument similar to the 'result' string, or you can staple the figures to 'result' itself for a convenient way to test without changing any architecture?

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionalitiy)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist
- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [x] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md)_

2020-10-28 18:15 UTC, tkkuehn reviewed
Really nice work! The output graphs look super nice. I have a few comments on this as is, which I'll put here for reference, then address before moving on to integrating this with the existing site.

2020-10-28 18:15 UTC, tkkuehn commented on generate_visualizations.py
> +generate_visualizations()
This is okay for testing, but should remove once this is integrated into the main validator

2020-11-11 19:12 UTC, tkkuehn commented
Alrighty, I think this is in shape for a review now.

2020-11-11 19:26 UTC, kaitj reviewed
Code wise, it looks good to me - have not had a chance to look at it locally yet (maybe a quick demo on the next call?). 

One thought, though it doesn't have to be changed for this PR, for the `generate_visualizations`, wondering if it might be a good idea to have separate functions / more meaningful names in case more figures are to be added in the future?

2020-11-11 20:07 UTC, tkkuehn commented
Notes from today's meeting:

- Put table back
- Label colorbar
- Remove tiny text on histogram

2020-11-11 20:08 UTC, kaitj requested changes
Clean up code (see meeting minutes & @tkkuehn's comments)

2020-11-19 21:26 UTC, tkkuehn commented
I think this is ready for another review!

2020-11-20 15:05 UTC, kaitj reviewed
Looks great, both code and actual site. Changes look good to me, and good to merge. Will note some of the code will likely need to be changed with the creation of an afids class (#101). Wondering do we want to merge it into master now, or release it as part of 0.2.x?

2020-11-20 15:32 UTC, tkkuehn commented
> Wondering do we want to merge it into master now, or release it as part of 0.2.x?

Either way seems fine to me. We could even merge this, make it 0.2.0, then make the AFIDs class stuff 0.3.0.

2020-11-20 15:53 UTC, kaitj commented
Given that I somehow did some weird thing with creating the AFIDs class and this doesn't actually break functionality with 0.1.x (though it is a major enhancement), I'd be happy with merging this in as 0.1.x and still call the AFIDs class 0.2.x

2020-11-25 14:15 UTC, tkkuehn commented
Great, feel free to merge and tag it as a new release in that case!

2020-11-25 20:52 UTC, kaitj approved these changes

2020-11-25 20:52 UTC, merged